apiVersion: 1

providers:
 - name: 'apis'
   orgId: 1
   folder: 'Akamai APIs'
   folderUid: ''
   type: file
   allowUiUpdates: true
   options:
        path: /var/lib/grafana/dashboards/apis
        