{
 "title": "Chrome User Experience",
 "tags": [
  "CrUX",
  "Chrome User Experience"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testtype",
    "label": "Test Type",
    "query": {}
   },
   {
    "name": "testname",
    "label": "Test Name",
    "query": {}
   },
   {
    "name": "domains",
    "label": "Domains",
    "query": {}
   },
   {
    "name": "pages",
    "label": "Pages",
    "query": {}
   },
   {
    "name": "device",
    "label": "Device",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Origin Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DESKTOP - Origin Data",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Results over the last 30 days for Chrome users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.FIRST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.FIRST_INPUT_DELAY_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.INTERACTION_TO_NEXT_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.LARGEST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.DESKTOP.TIME_TO_FIRST_BYTE_MS.p75"
    }
   ]
  },
  {
   "title": "PHONE - Origin Data",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Results over the last 30 days for Chrome users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.FIRST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.FIRST_INPUT_DELAY_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.INTERACTION_TO_NEXT_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.LARGEST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.PHONE.TIME_TO_FIRST_BYTE_MS.p75"
    }
   ]
  },
  { "title": "Page Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DESKTOP - Page Data",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Pages that have recorded CrUX data at the 75th percentile",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.FIRST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.FIRST_INPUT_DELAY_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.INTERACTION_TO_NEXT_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.LARGEST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.DESKTOP.TIME_TO_FIRST_BYTE_MS.p75"
    }
   ]
  },
  {
   "title": "PHONE - Page Data",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Pages that have recorded CrUX data at the 75th percentile",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.FIRST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.FIRST_INPUT_DELAY_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.INTERACTION_TO_NEXT_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.LARGEST_CONTENTFUL_PAINT_MS.p75"
    },
    {
     "target": "sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.PHONE.TIME_TO_FIRST_BYTE_MS.p75"
    }
   ]
  },
  { "title": "LCP Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.p75, 5)"
    }
   ]
  },
  { "title": "LCP Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.LARGEST_CONTENTFUL_PAINT_MS.p75, 6)"
    }
   ]
  },
  { "title": "CLS Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 5)"
    }
   ]
  },
  { "title": "CLS Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 161 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 6)"
    }
   ]
  },
  { "title": "FID Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 261 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_INPUT_DELAY_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_INPUT_DELAY_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_INPUT_DELAY_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_INPUT_DELAY_MS.p75, 5)"
    }
   ]
  },
  { "title": "FID Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 280 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 281 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_INPUT_DELAY_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_INPUT_DELAY_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_INPUT_DELAY_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 369 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_INPUT_DELAY_MS.p75, 6)"
    }
   ]
  },
  { "title": "TTFB Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 380 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 381 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.TIME_TO_FIRST_BYTE_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.TIME_TO_FIRST_BYTE_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.TIME_TO_FIRST_BYTE_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 389 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.TIME_TO_FIRST_BYTE_MS.p75, 5)"
    }
   ]
  },
  { "title": "TTFB Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 401 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.TIME_TO_FIRST_BYTE_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.TIME_TO_FIRST_BYTE_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.TIME_TO_FIRST_BYTE_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 489 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.TIME_TO_FIRST_BYTE_MS.p75, 6)"
    }
   ]
  },
  { "title": "FCP Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 501 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 509 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.p75, 5)"
    }
   ]
  },
  { "title": "FCP Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 520 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 521 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 609 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.FIRST_CONTENTFUL_PAINT_MS.p75, 6)"
    }
   ]
  },
  { "title": "INP Origin Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 620 } },
  {
   "title": "$device - $domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 621 },
   "repeat": "domains",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 629 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.summary.$domains.crux.originLoadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.p75, 5)"
    }
   ]
  },
  { "title": "INP Page Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 640 } },
  {
   "title": "$device - $domains - $pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 641 },
   "repeat": "pages",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.fast, 'Fast')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.moderate, 'Moderate')"
    },
    {
     "target": "alias(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.slow, 'Slow')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 729 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.$testtype.$testname.PSI-CrUX.pageSummary.$domains.$pages.crux.loadingExperience.$device.INTERACTION_TO_NEXT_PAINT_MS.p75, 6)"
    }
   ]
  }
 ]
}