{
 "title": "Geographic Performance",
 "tags": [ "Geography" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "sitespeed_io" },
   {
    "name": "path",
    "label": "Test Type",
    "query": {}
   },
   {
    "name": "testname",
    "label": "Test Name",
    "query": {}
   },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "group",
    "label": "Domain",
    "query": {}
   },
   {
    "name": "page",
    "label": "Page",
    "query": {}
   },
   { "name": "function", "label": "Percentile", "query": "mean,p25,p50,p75,p95" },
   {
    "name": "metric",
    "label": "Web Metric",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Performance by Page/Company", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$testname - $metric - LAN",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.*.*.chrome.LAN.browsertime.statistics.googleWebVitals.$metric.$function"
    }
   ]
  },
  {
   "title": "$testname - $metric - Mobile",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.*.*.chrome.LTE.browsertime.statistics.googleWebVitals.$metric.$function"
    }
   ]
  },
  { "title": "Performance by Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$group - $page - LAN",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LAN.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LAN.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LAN.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LAN.browsertime.statistics.googleWebVitals.ttfb.$function"
    }
   ]
  },
  {
   "title": "$group - $page - Mobile",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LTE.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LTE.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LTE.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function"
    },
    {
     "target": "$namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LTE.browsertime.statistics.googleWebVitals.ttfb.$function"
    }
   ]
  },
  {
   "title": "$group - $page - $metric - LAN",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LAN.browsertime.statistics.googleWebVitals.$metric.$function, 3)"
    }
   ]
  },
  {
   "title": "$group - $page - $metric - Mobile",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.chrome.LTE.browsertime.statistics.googleWebVitals.$metric.$function, 3)"
    }
   ]
  }
 ]
}