apiVersion: 1

providers:
 - name: 'google'
   orgId: 1
   folder: 'Google'
   folderUid: ''
   type: file
   allowUiUpdates: true
   options:
        path: /var/lib/grafana/dashboards/google
        