apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1
    
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    basicAuth: false
    orgId: 1
    uid: Qotwtdl7z
    url: http://localhost:8888
    isDefault: true
    jsonData:
      graphiteVersion: '1.1'
      graphiteType: 'default'