{
 "title": "Leaderboard",
 "tags": [ "Leaderboard" ],
 "time": { "from": "2023-07-13T23:33:01.035Z", "to": "2023-07-25T16:22:26.006Z" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "sitespeed_io" },
   { "name": "path", "label": "Test Type", "query": "$namespace.*" },
   { "name": "testname", "label": "Test Name", "query": "$namespace.$path.*" },
   {
    "name": "domains",
    "label": "Domains",
    "query": "$namespace.$path.$testname.$region.pageSummary.*"
   },
   {
    "name": "pages",
    "label": "Pages",
    "query": "$namespace.$path.$testname.$region.pageSummary.$domains.*"
   },
   { "name": "region", "label": "Region", "query": "$namespace.$path.$testname.*" },
   {
    "name": "browser",
    "label": "Browser",
    "query": "$namespace.$path.$testname.$region.pageSummary.$domains.$pages.*"
   },
   { "name": "function", "label": "Percentile", "query": "mean,p25,p50,p75,p95" },
   {
    "name": "connectivity",
    "label": "Connectivity",
    "query": "$namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.*"
   }
  ]
 },
 "panels": [
  { "title": "Visual Metrics - Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First Visual Change",
   "type": "bargauge",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 'average'),6)"
    }
   ]
  },
  {
   "title": "Time for Largest Image",
   "type": "bargauge",
   "description": "The largest image is the time when the largest image within the viewport is painted and on its final position. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function,'average'),6)"
    }
   ]
  },
  {
   "title": "Speed Index - $connectivity",
   "type": "bargauge",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function,'average'), 6)"
    }
   ]
  },
  {
   "title": "Visual Readiness",
   "type": "bargauge",
   "description": "Visual readiness is the time between the first visual change and the last visual change within the viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualReadiness.$function,'average'), 6)"
    }
   ]
  },
  { "title": "Visual Metrics - Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "First Visual Change",
   "type": "timeseries",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function,6)"
    }
   ]
  },
  {
   "title": "Largest Image",
   "type": "timeseries",
   "description": "The largest image is the time when the largest image within the viewport is painted and on its final position. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 6)"
    }
   ]
  },
  {
   "title": "SpeedIndex",
   "type": "timeseries",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 6)"
    }
   ]
  },
  {
   "title": "Visual Readiness",
   "type": "timeseries",
   "description": "Visual readiness is the time between the first visual change and the last visual change within the viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualReadiness.$function, 6)"
    }
   ]
  },
  { "title": "Page Metrics - Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Time to First Byte",
   "type": "bargauge",
   "description": "Fully loaded time when the last of all assets is downloaded on the page.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.ttfb.$function, 'average'), 6)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "bargauge",
   "description": "Fully loaded time when the last of all assets is downloaded on the page.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, 'average'), 6)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function, 'average'), 6)"
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "bargauge",
   "description": "Fully loaded time when the last of all assets is downloaded on the page.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function,'average'), 6)"
    }
   ]
  },
  {
   "title": "Load Event End",
   "type": "bargauge",
   "description": "Load Event End is when the load event end event fires in the Navigation Timing API",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function,'average'), 6)"
    }
   ]
  },
  { "title": "Page Metrics - Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.ttfb.$function, 6)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, 6)"
    }
   ]
  },
  {
   "title": "Load Event End",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function, 6)"
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 6)"
    }
   ]
  },
  { "title": "JavaScript - Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Script Processing Time - $connectivity",
   "type": "bargauge",
   "description": "CPU time spent evaluating JavaScript. Calculated using [Tracium](https://github.com/aslushnikov/tracium). This is a Chrome only metric at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.categories.scriptEvaluation.$function,'average'), 6)"
    }
   ]
  },
  {
   "title": "Total Blocking Time",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortByTotal(aliasByNode($namespace.$path.$testname.$region.pageSummary.*.$pages.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, 6))"
    }
   ]
  },
  {
   "title": "JavaScript Transfer Size",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize,'average'), 6)"
    }
   ]
  },
  {
   "title": "JavaScript Content Size",
   "type": "bargauge",
   "description": "The JavaScript size unpacked.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize,'average'), 6)"
    }
   ]
  },
  {
   "title": "Requests and Page Size - Leaders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 }
  },
  {
   "title": "Requests",
   "type": "bargauge",
   "description": "Total number of requests for the full page.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 161 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests,'average'), 6)"
    }
   ]
  },
  {
   "title": "Transfer Size",
   "type": "bargauge",
   "description": "Total page weight (compressed over the wire).",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize,'average'), 6)"
    }
   ]
  },
  {
   "title": "Requests and Page Size - Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 }
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests, 6)"
    }
   ]
  },
  {
   "title": "Transfer Size",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize, 6)"
    }
   ]
  },
  { "title": "Requests and Page Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "Number of Requests",
   "type": "stat",
   "description": "Total number of requests for the full page.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests, 6), 'avg', false)"
    }
   ]
  },
  {
   "title": "Page Transfer Size",
   "type": "stat",
   "description": "Total page weight (compressed over the wire).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize, 6), 'average', false)"
    }
   ]
  },
  { "title": "CPU - Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "title": "Total Long Tasks - $connectivity",
   "type": "bargauge",
   "description": "The average number of CPU Long Tasks per page. A CPU long Task is by default a CPU task that takes longer than 50 ms to run. This metrics is Chrome only at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function,'average'), 6)"
    }
   ]
  },
  {
   "title": "Long Tasks before LCP - $connectivity",
   "type": "bargauge",
   "description": "Average Number of Long Tasks that occur before LCP",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode($namespace.$path.$testname.$region.pageSummary.*.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeLargestContentfulPaint.tasks.$function, 6), 'average', false)"
    }
   ]
  },
  {
   "title": "Longest Long Task",
   "type": "bargauge",
   "description": "This is the longest CPU task for each page (if they are over 50 ms long). This metrics is Chrome only at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.$function,'average'), 6)"
    }
   ]
  },
  {
   "title": "Rendering Time",
   "type": "bargauge",
   "description": "CPU time spent rendering the page. Calculated using [Tracium](https://github.com/aslushnikov/tracium). This is a Chrome only metric at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.categories.paintCompositeRender.$function,'average'), 6)"
    }
   ]
  },
  { "title": "CPU Long Task - Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 } },
  {
   "title": "Longest CPU Long Tasks",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.$function, 6)"
    }
   ]
  },
  {
   "title": "Number of CPU Long Tasks",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 6)"
    }
   ]
  },
  {
   "title": "Number of CPU Long Tasks before LCP",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeLargestContentfulPaint.tasks.$function, 6)"
    }
   ]
  },
  { "title": "Third Party Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 } },
  {
   "title": "Third Party Requests - $connectivity",
   "type": "bargauge",
   "description": "Third party requests are calculated using the [Third party web](https://github.com/patrickhulce/third-party-web) library. \n\nNOTE - Changing the percentile will have no affect on the value",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.thirdparty.requests.total.mean, 'average'), 6)"
    }
   ]
  },
  {
   "title": "% Third Party Requests - $connectivity",
   "type": "bargauge",
   "description": "Third party % are calculated using the [Third party web](https://github.com/patrickhulce/third-party-web) library.\n\nNOTE - Changing the percentile will have no affect on the value",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.thirdparty.requests.percentage.mean, 'average'), 6)"
    }
   ]
  },
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 273 } },
  {
   "title": "Performance Score",
   "type": "bargauge",
   "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 274 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.coach.advice.performance.score, 'average', true),6)"
    }
   ]
  },
  {
   "title": "Privacy Score",
   "type": "bargauge",
   "description": "The privacy score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using user privacy best practices.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 274 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.$region.pageSummary.$domains.$pages.$browser.$connectivity.coach.advice.privacy.score, 'average', true), 6)"
    }
   ]
  }
 ]
}