{
 "title": "Page Metrics",
 "tags": [
  "Page Metrics",
  "Verizon"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "sitespeed_io" },
   { "name": "path", "label": "Test Type", "query": "$namespace.*" },
   { "name": "testname", "label": "Test Name", "query": "$namespace.$path.*" },
   {
    "name": "group",
    "label": "Domain",
    "query": "$namespace.$path.$testname.$region.pageSummary.*"
   },
   {
    "name": "page",
    "label": "Page",
    "query": "$namespace.$path.$testname.$region.pageSummary.$group.*"
   },
   { "name": "region", "label": "Region", "query": "$namespace.$path.$testname.*" },
   {
    "name": "browser",
    "label": "Browser",
    "query": "$namespace.$path.$testname.$region.pageSummary.$group.$page.*"
   },
   {
    "name": "connectivity",
    "label": "Connectivity",
    "query": "$namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.*"
   },
   { "name": "function", "label": "Percentile", "query": "p25,mean,median,p75,p95" },
   { "name": "resulturl", "query": "DOMAIN/images" },
   { "name": "screenshottype", "query": "png" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visual Metrics",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, \"First Visual Change\")"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestContentfulPaint.$function,  \"Largest Contentful Paint\")"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, \"Largest Image\")"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, \"Speed Index\")"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.firstPaint.$function, \"First Paint\")"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.$function, \"TTFB\")"
    }
   ]
  },
  {
   "title": "Screenshot",
   "type": "text",
   "description": "Screenshot of the latest test",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": {
    "content": "<a href=\"http://$region.$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\">\n<img src=\"http://$region.$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\"></a>"
   },
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 8)"
    }
   ]
  },
  {
   "title": "Video",
   "type": "text",
   "description": "Video of the loading process of the latest test",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<video controls width=\"100%\"src=\"http://$region.$resulturl/$testname/$group.$page.$browser.$connectivity.mp4\"></video>\n"
   },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domElements, 'DOM elements')"
    }
   ]
  },
  {
   "title": "LCP Image",
   "type": "text",
   "description": "Highlighted LCP image from the latest test",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": {
    "content": "<a href=\"http://$region.$resulturl/$testname/$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\">\n<img src=\"http://$region.$resulturl/$testname/$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\"></a>"
   },
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 8)"
    }
   ]
  },
  {
   "title": "Visual Layout Shifts",
   "type": "text",
   "description": "Highlighted layout shifts from the latest test",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": {
    "content": "<a href=\"http://$region.$resulturl/$testname/$group.$page.layoutShift.$browser.$connectivity.$screenshottype\">\n<img src=\"http://$region.$resulturl/$testname/$group.$page.layoutShift.$browser.$connectivity.$screenshottype\"></a>"
   },
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 8)"
    }
   ]
  },
  {
   "title": "Page Info",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Web Vitals",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize, 'Transfer Size')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 'Requests')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.requests, 'First Party Requests')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.requests, 'Third Party Requests')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, 'LCP')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, 'TBT')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function, 'CLS')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.$function, 'TTFB')"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "description": "All requests and their HTTP Status Code",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "groupByNode(summarize(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.responseCodes.*, 5), '1h', 'sum', false), 11, 'sum')"
    }
   ]
  },
  { "title": "Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "First Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function, '24h'), 'Last 24 hours')"
    },
    {
     "target": "alias(timeShift(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function, '24h'), '7d'), 'One Week Earlier')"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.paintTiming.first-contentful-paint.$function, 'FCP')"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, '24h'), 'Last 24 hours')"
    },
    {
     "target": "alias(timeShift(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, '24h'), '7d'), 'One Week Earlier')"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 'LCP')"
    }
   ]
  },
  {
   "title": "Total Blocking Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, '24h'), 'Last 24 hours')"
    },
    {
     "target": "alias(timeShift(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, '24h'), '7d'), 'One Week Earlier')"
    }
   ]
  },
  {
   "title": "Total Blocking Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'TBT')"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function, '24h'), 'Last 24 hours')"
    },
    {
     "target": "alias(timeShift(movingAverage($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function, '24h'), '7d'), 'One Week Earlier')"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.pageinfo.cumulativeLayoutShift.$function, 'CLS')"
    }
   ]
  },
  { "title": "Requests and Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.requests, 11)"
    }
   ]
  },
  {
   "title": "Transfer Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.transferSize, 11)"
    }
   ]
  },
  {
   "title": "Content Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.contentSize, 11)"
    }
   ]
  },
  {
   "title": "Requests per Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.requests, 11)"
    }
   ]
  },
  {
   "title": "Transfer Size per Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.transferSize, 11)"
    }
   ]
  },
  {
   "title": "Content Size per Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.contentSize, 11)"
    }
   ]
  },
  { "title": "Page Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "type": "stat",
   "description": "The document height in pixels.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.documentHeight, 'Document Height')"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The max depth of DOM elements on the page.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.max, 'Max DOM Depth')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.localStorageSize, 'Local Storage Size')"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The total number of iframes used on the page.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.iframes, 'iFrames')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.totalDomains, 'Domains')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.cookies, ' First Party Cookies')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.cookies, 'Third Party Cookies')"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The $function cache expire time for all responses on the page.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.expireStats.median, 'Cache Expiration')"
    }
   ]
  },
  {
   "title": "Page Timings",
   "type": "timeseries",
   "description": "Timing metrics collected using browser APIs like the Navigation Timing API.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 'Fully Loaded')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.firstPaint.$function, 'Time to First Paint')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 'Largest Contentful Paint')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function, 'Load Event Complete')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domContentLoadedTime.$function, 'DOM Content Loaded')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, 'Server Response Time')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domInteractiveTime.$function, 'DOM Interactive')"
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.cookies, 'First Party')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.cookies, 'Third Party')"
    }
   ]
  },
  { "title": "Third Party", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Requests by Category",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.thirdparty.category.*.requests.$function, 11)"
    }
   ]
  },
  {
   "title": "Time Spent per Third Party",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.thirdparty.tool.*.cpu.$function, 11)"
    }
   ]
  },
  { "title": "Navigation Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Navigation Timings",
   "type": "timeseries",
   "description": "Metrics collected from theNavigation Timing API",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.navigationTiming.*.$function, 13)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 'Total Long Tasks')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.$function, 'Longest Long Task')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeLargestContentfulPaint.tasks.$function, 'Long Tasks Before LCP')"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.garbageCollection.$function, 'Garbage Collection')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.paintCompositeRender.$function, 'Paint Composite Render')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.parseHTML.$function, 'Parse HTML')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.scriptEvaluation.$function, 'Script Evaluation')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.scriptParseCompile.$function, 'Script Parse & Compile')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.styleLayout.$function, 'Layout')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "The CPU metrics are collected from Chrome when you add --chrome.timeline to your run. The trace log is analyzed and sorted by type.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.events.*.median, 13)"
    }
   ]
  },
  { "title": "JavaScript", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapTotalSize.$function, 'Total JS Heap Size')"
    },
    {
     "target": "alias($namespace.$path.$testname.$region.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapUsedSize.$function, 'Used JS Heap Size')"
    }
   ]
  }
 ]
}