apiVersion: 1

providers:
 - name: 'sitespeed'
   orgId: 1
   folder: 'Sitespeed'
   folderUid: ''
   type: file
   allowUiUpdates: true
   options:
        path: /var/lib/grafana/dashboards/sitespeed
        