{
 "title": "Sitespeed Monitor",
 "tags": [
  "admin",
  "monitor"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "sitespeed_log" },
   { "name": "path", "label": "Test Type", "query": "$namespace.*" },
   { "name": "testname", "label": "Test Name", "query": "$namespace.$path.*" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Test Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$testname Test Duration",
   "type": "stat",
   "description": "$testname test duration of the latest test. This includes the aggregate of both LAN and LTE.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode(sitespeed_log.$path.$testname.*.duration, 3), 'current', true)"
    }
   ]
  },
  {
   "title": "$testname Test Duration Over Time",
   "type": "timeseries",
   "description": "Duration of test run, which includes LAN and LTE",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "target": "aliasByNode(sitespeed_log.$path.$testname.*.duration, 3)"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Database Sizes",
   "type": "stat",
   "description": "Most current size of disk usage fr each entity being collected",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_log.disk, 'Sitespeed')"
    },
    {
     "target": "alias(sitespeed_log.Competitors.disk, 'Competitors')"
    },
    {
     "target": "alias(sitespeed_log.TLD.disk, 'TLD')"
    }
   ]
  },
  {
   "title": "Database Growth Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "target": "alias(sitespeed_log.disk, 'Sitespeed')"
    },
    {
     "target": "alias(sitespeed_log.Competitors.disk, 'Competitors')"
    },
    {
     "target": "alias(sitespeed_log.TLD.disk, 'TLD')"
    }
   ]
  },
  { "title": "Database Size by Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Database Sizes",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "target": "sitespeed_log.*.comp" },
    { "target": "sitespeed_log.*.tld" },
    { "target": "sitespeed_log.*.images" }
   ]
  },
  {
   "title": "$region Database Size",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sitespeed_log.$region.comp, 'Competitors')"
    },
    {
     "target": "alias(sitespeed_log.$region.tld, 'TLD')"
    },
    {
     "target": "alias(sitespeed_log.$region.images, 'Images')"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Errors by Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode(sitespeed_log.*.errors, 1), 'total', true)"
    }
   ]
  },
  {
   "title": "Errors by Server Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sortBy(aliasByNode(sitespeed_log.*.errors, 1), 'total', true)"
    }
   ]
  },
  {
   "title": "Core Dumps on Each Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByNode(sitespeed_log.*.core, 1), 'total', true)"
    }
   ]
  },
  {
   "title": "Core Dumps on Each Server Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sortBy(aliasByNode(sitespeed_log.*.core, 1), 'total', true)"
    }
   ]
  },
  { "title": "Graphite", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "target": "carbon.agents.*.cpuUsage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "target": "carbon.agents.*.memUsage" }
   ]
  },
  {
   "title": "Metrics Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "stats.statsd.metrics_received" }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.response.*, 2)"
    }
   ]
  }
 ]
}